-- 보안/사용자 기준 테이블
CREATE TABLE IF NOT EXISTS PUBLIC.ROLE
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLENAME CHARACTER VARYING(255)
        CONSTRAINT UK_NFWGTW7JN5H1ILUD74CRAQ02Q UNIQUE
);

CREATE TABLE IF NOT EXISTS PUBLIC.AUTHORITY
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    ALIAS       CHARACTER VARYING(255)
        CONSTRAINT UK_E7P16L22BNDBNBM1HD5DAHK42 UNIQUE,
    AUTHORITY   CHARACTER VARYING(255)
        CONSTRAINT UK_MH4UJP6XCTMCXE3UP55NKW7BW UNIQUE,
    CODE        CHARACTER VARYING(255)
        CONSTRAINT UK_SOEHEY9TMTYDMALWNIWQKWFT1 UNIQUE,
    DESCRIPTION CHARACTER VARYING(255),
    STATUS      CHARACTER VARYING(255),
    CHECK ("AUTHORITY" IN (
        'AUTH_SPECIAL_FOR_TEST',
        'AUTH_RETRIEVE_USER_ALL_FOR_MARKETING',
        'AUTH_RETRIEVE_USER_ALL_FOR_DELIVERY'
    ))
);

CREATE TABLE IF NOT EXISTS PUBLIC.TERMS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    TERMSNAME CHARACTER VARYING(255)
        CONSTRAINT UK_DKKFK1DYLSEVS9OVOIEV9FTT2 UNIQUE
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL    CHARACTER VARYING(255)
        CONSTRAINT UK_AVH1B2EC82AUDUM2LYJX2P1WS UNIQUE,
    NAME     CHARACTER VARYING(255),
    PASSWORD CHARACTER VARYING(255)
);

-- 보안/사용자 관계 테이블
CREATE TABLE IF NOT EXISTS PUBLIC.ROLE_AUTHORITY_MAP
(
    ROLE_ID      BIGINT NOT NULL,
    AUTHORITY_ID BIGINT NOT NULL,
    CONSTRAINT FK6FRMLM7LF2UL6UVAS8MY4R5RX
        FOREIGN KEY (ROLE_ID) REFERENCES PUBLIC.ROLE (ID),
    CONSTRAINT FKEFFDNWYU4LUWA4DKTNF43LI8H
        FOREIGN KEY (AUTHORITY_ID) REFERENCES PUBLIC.AUTHORITY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_ROLE_MAP
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT FK2OKLONXJSUPRETBDYM1JSOATH
        FOREIGN KEY (ROLE_ID) REFERENCES PUBLIC.ROLE (ID),
    CONSTRAINT FKA74WSU6BB10J9CLLTOGNJ89DN
        FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_TERMS_MAP
(
    USER_ID  BIGINT NOT NULL,
    TERMS_ID BIGINT NOT NULL,
    CONSTRAINT FK5EBF2OSVN36NW21KJND0U8J4X
        FOREIGN KEY (TERMS_ID) REFERENCES PUBLIC.TERMS (ID),
    CONSTRAINT FK6TYX5KY82RE8OHTGANKVJ1HC3
        FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_ADDRESS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    ADDRESS     CHARACTER VARYING(255),
    ADDRESSTYPE CHARACTER VARYING(255),
    USER_ID     BIGINT,
    CONSTRAINT FK36X9E9N4VLIYESQXBJ5CC8AXD
        FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (ID)
);

-- 게시판 예제 테이블
CREATE TABLE IF NOT EXISTS PUBLIC.POST_EXAMPLE
(
    POST_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOARD_ID   INT,
    BOARD_NAME CHARACTER VARYING(100),
    CREATE_AT  TIMESTAMP NOT NULL,
    UPDATE_AT  TIMESTAMP NOT NULL,

    USER_ID    BIGINT NOT NULL,
    USER_EMAIL CHARACTER VARYING(255),
    USER_NAME  CHARACTER VARYING(255),

    TITLE      CHARACTER VARYING(200),
    CONTENT    TEXT
);

CREATE TABLE IF NOT EXISTS PUBLIC.POST_FILES
(
    POST_ID    BIGINT NOT NULL,
    BOARD_ID   INT,

    FILE_NAME  CHARACTER VARYING(255),
    FILE_ORDER INT,
    FILE_PATH  CHARACTER VARYING(255),

    CONSTRAINT FK_POSTFILES_POST
        FOREIGN KEY (POST_ID) REFERENCES PUBLIC.POST_EXAMPLE (POST_ID)
);

-- 단순 예제 테이블
CREATE TABLE IF NOT EXISTS PUBLIC.PHONEBOOK
(
    USER_NAME    CHARACTER VARYING(50) NOT NULL,
    PHONE_NUMBER CHARACTER VARYING(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.TEST
(
    C1 CHARACTER VARYING(10),
    C2 CHARACTER VARYING(10),
    C3 CHARACTER VARYING(10)
);

CREATE TABLE IF NOT EXISTS PUBLIC.TESTJPA
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    MYKEY   CHARACTER VARYING(255)
        CONSTRAINT UK_AFXEL70FY7OO8G35IKAL4XN5U UNIQUE,
    MYVALUE CHARACTER VARYING(255)
);
