spring:
  sql:
    init:
      mode: always #(always, never, embedded)
      schema-locations: classpath:_sptek/_webFrameworkExample/_h2SqlInitialization/schema*.sql
      data-locations: classpath:_sptek/_webFrameworkExample/_h2SqlInitialization/data*.sql
