project-info:
  app:
    name: SPT Framework Web Core
    version: v1.0.0
    description : enjoy your coding life with SPT Framework Web Core

server:
  name: ${HOSTNAME:${COMPUTERNAME:unknown}}
  port: 443
  shutdown: graceful
  tomcat:
    threads:
      max: 10 # 동시에 처리할 수 있는 서블릿 디스패처 최대 worker thread 수 (기본 200)
      min-spare: 10 # 최소로 항상 유지하는 서블릿 디스패처 최대 worker thread 수 (기본 10)

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s #graceful 최대 대기 시간 (반드시 s를 붙일것)
  devtools:
    livereload.enabled: true
    restart.enabled: true
  config:
    import:
      #_sptek/__webFramework
      - optional:classpath:_autoSqlInitialize/autoSqlInitialize.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/actuator/actuator.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/frameworkPackage/frameworkPackage.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/globalError/globalError.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/h2DB/h2DB.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/jsp/jsp.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/pageHelper/pageHelper.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/ssl/ssl.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/thymeleaf/thymeleaf.yml
      #cesco/__projectsCommon(_system)
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/cors/corsPolicy.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/daoPagination/daoPagination.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/datasource/datasource.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/encryption/encryption.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/jpa/jpa.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/jwt/jwt.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/logging/logging.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/mybatis/mybatis.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/outbound/outbound.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/session/session.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/swagger/swagger.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/storage/storage.yml
      - optional:classpath:_sptek/_webFrameworkExample/applicationProperties/viewModelAttribute/viewModelAttribute.yml
      #cesco/__projectsCommon(extra)
